### ISSUE TITLE
Adding "advancedPHP" to your Theme

### ISSUE THREAD

**Issue by dennisosaj** [blakewatson/nova-tomorrow-night-eighties#1]
Heyho,
I saw your theme and noticed a growing popularity.

I'm asking if you could add "advancedPHP" to your theme. It's one of my own extensions and I want to provide more theme coverage for my users.

You can find a theme development documentation in its repo: https://github.com/dennisosaj/advancedphp.novaextension

I would really appreciate it. Thanks!

**Comment by blakewatson** [comment]
@dennisosaj Nice! I will def consider this. Thanks for bringing it to my attention.

**Comment by blakewatson** [comment]
@dennisosaj Working on adding support. Got a question for you. I'd like to be able to target PHP tags (`<?php ?>` and `<?= ?>`) separately from regular brackets. Do you know if that’s possible?

**Comment by blakewatson** [comment]
> @dennisosaj Working on adding support. Got a question for you. I'd like to be able to target PHP tags (`<?php ?>` and `<?= ?>`) separately from regular brackets. Do you know if that’s possible?

I’ve added preliminary support but I would still like this ability if it’s doable.

**Comment by dennisosaj** [comment]
@blakewatson it is possible in general, but not supported yet. Will consider it for the next minor update. Downside is that every theme developer must adjust their styles. Unfortunately there is no fallback or double naming possible.

Also, your theme looks awesome with advanced PHP. Super nice job!

**Comment by blakewatson** [comment]
@dennisosaj gotcha, well I think I found a decent color for all brackets but yeah if that’s feature ever drops I have another color in mind. Thanks for the kind words and also a sweet Nova extension!
